[package]
name = "weto-guard"
version = "0.0.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true

[dependencies]
weto-core = { path = "../weto-core" }
weto-sys = { path = "../weto-sys" }
weto-config = { path = "../weto-config" }

[dev-dependencies]
tempfile = { workspace = true }
